import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Nav from "./nav";
import React from "react";
import {AuthProvider} from "./context/AuthContext";
import {UserProvider} from "./context/UserContext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<AuthProvider>
			<UserProvider>
				<Nav/>
				<div id={"main"} className={"mt-8"}>
					{children}
				</div>
			</UserProvider>
		</AuthProvider>
		</body>
		</html>
	);
}
