name: Playwright Tests

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

  test:
    needs: [vercel,setup]
    runs-on: ubuntu-latest

    steps:
      - name: Run Playwright tests
        run: npm run playwright
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
